name: Validate Changes

on:
  push:
    paths:
      - '**.json'
    branches:
      - main
      - Release
    
  pull_request:
    paths:
      - '**.json'
      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v3
        with:
          file: '**.json'
          
      - name: Validate butane files using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: '**.bu'
          schema: './Butane-Schema-dev.json'
          mode: default
