name: Validate Changes

on:
  push:
    paths:
      - '**.json'
    branches:
      - main
      - Release
    
  pull_request:
    paths:
      - '**.json'
      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'v*/*.json|*.json'
          
      - name: Validate CoreOS butane v1.4 file using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'v1.4.0/testconfig.bu'
          schema: 'v1.4.0/butane-v1.4.0.json'
          mode: lax
          
      - name: Validate CoreOS butane v1.5 file using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'v1.5.0/testconfig.bu'
          schema: 'v1.5.0/butane-v1.5.0.json'
          mode: lax

      - name: Validate CoreOS butane v1.6 file using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'v1.6.0/testconfig.bu'
          schema: 'v1.6.0/butane-v1.6.0.json'
          mode: lax

      - name: Validate flatcar butane v1.1.0 file using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: 'flatcar-v1.1.0/butane-flatcar-v1.1.0.json'
          schema: 'v1.1.0/butane-v1.6.0.json'
          mode: lax
