name: Validate Changes

on:
  push:
    paths:
      - '**.json'
    branches:
      - main
      - Release
    
  pull_request:
    paths:
      - '**.json'
      
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Validate all json files using their own $schema properties
        uses: cardinalby/schema-validator-action@v3
        with:
          file: '**.json|**/*.json'
          fileParser: json
          
      - name: Validate butane files using associated json schema
        uses: cardinalby/schema-validator-action@v3
        with:
          file: '**/*.bu'
          fileParser: yaml
          schema: './Butane-Schema-actions.json'
          mode: default
          refSchemasMap: |
            '{"./v1.4.0/butane-v1.4.0.json": "./v1.4.0/butane-v1.4.0.json"},
            {"./v1.5.0/butane-v1.5.0.json": "./v1.5.0/butane-v1.5.0.json"},
            {"./v1.6.0/butane-v1.6.0.json": "./v1.6.0/butane-v1.6.0.json"}'


# "./flatcar-v1.1.0/butane-flatcar-v1.1.0.json"]